name: Release Build
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  release:
    types:
      - created

permissions:
  contents: write

env:
  ATUN_LOG_PLAIN_TEXT: true

jobs:
  goreleaser:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Dry Run Release
        run: |
          echo "This is a dry run release. Will be activated after dev builds are stable"
          echo GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
          echo RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          echo GIT_SHA: ${{ env.SHORT_SHA }}
          echo GITHUB_ACTOR: ${{ github.actor }}

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          RELEASE_VERSION: "${{ env.RELEASE_VERSION }}"
          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
          GIT_SHA: ${{ env.SHORT_SHA }}
          GITHUB_ACTOR: ${{ github.actor }}


      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ env.RELEASE_VERSION }}" --draft=false --latest=false
